---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ17N18"
  stages:
    Release:
      cfCredentialsId: "gitcreads1"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cloudFoundryDeploy: false
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: false
  Release:
    tmsExport: false
    tmsUpload: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com/"
    cfOrg: "0c608e5ctrial"
    cfSpace: "Fiori"
    deployType: "standard"
    cloudFoundryDeploy: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: false
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
